using UnityEngine;
using System.Collections;

// Keeps track of the player's noise level on a scale of 1 - 100
public class PlayerNoise : MonoBehaviour {
	// The current level of noise player is generating
	public int noiseLevel;
	// The player's character controller
	public CharacterController playerCharacter;
	
	// Noise level generated by water
	int waterNoise;
	// Noise level generated by leaves
	int leavesNoise;
	// Noise level generated by soft grass
	int grassNoise;
	
	// Use this for initialization
	void Start () {
		noiseLevel = 0;
	}
	
	// Update is called once per frame
	void Update () {
		NoiseInput();
	}
	
	// Calculate a base noise level based on current input keys
	void NoiseInput(){
		// If the player's velocity isn't a zero vector (AKA player is moving)
		if (!(playerCharacter.velocity == new Vector3(0, 0, 0))){
			
			// If the player isn't holding down the shift key, set the noise level to
			// 30 and add the noise level of triggered areas (if applicable).
			if (! (Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift))){
				noiseLevel = 30 + waterNoise + leavesNoise + grassNoise;
			}
			
			// If the player is holding down the shift key, set the noise level to
			// 0 and add the noise level of triggered areas (if applicable).
			if (Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift)){
				noiseLevel = 0 + waterNoise + leavesNoise + grassNoise;
			}
		}
	}
	
	// Once the player enters the trigger of an area that generates extra
	// noise, add to the noise level depending on what was stepped on.
	void OnTriggerEnter(Collider col){
		// If the player is moving through water, add 40 to the noise level
		if (col.gameObject.tag == "Water"){
			waterNoise = 40;
		}
		
		// If the player is moving through leaves, add 30 to the noise level
		if (col.gameObject.tag == "Leaves"){
			leavesNoise = 30;
		}
		
		// If the player is walking through soft grass, decrease 10 from the noise level
		if (col.gameObject.tag == "SoftGrass"){
			grassNoise = -10;
		}
	}
	
	// Once the player leaves these triggers, reset their values so they are
	// no longer included in the noise level calculations.
	void OnTriggerExit(Collider col){
		if (col.gameObject.tag == "Water"){
			waterNoise = 0;
		}
		
		if (col.gameObject.tag == "Leaves"){
			leavesNoise = 0;
		}
		
		if (col.gameObject.tag == "SoftGrass"){
			grassNoise = 0;
		}
	}
}
